name: Build Kernel Module
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Module
        run: |
          # البحث عن المجلد الذي يحتوي على ملف hci_qca.c
          DIR=$(find . -name "hci_qca.c" -exec dirname {} \;)
          echo "Found module in: $DIR"
          cd "$DIR"
          # بناء الملف
          make -C /lib/modules/$(uname -r)/build M=$PWD modules
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hci_qca_patched
          path: "**/hci_qca.ko"
